function getMockFlights(origin, destination, date) {
  return [
    {airline:"El Al",flightNumber:"LY315",origin,destination,departureTime:`${date}T11:30:00`,arrivalTime:`${date}T14:55:00`,departureHour:11,durationMinutes:265,stops:0,pricePerAdult:89,pricePerChild:67,totalPrice:312,baggageIncluded:true,baggageDetails:"1 carry-on + 1 checked bag 23kg. Stroller free at gate",seatsTogether:true,isSelfTransfer:false,seatsAvailable:4},
    {airline:"Lufthansa",flightNumber:"LH1302",origin,destination,departureTime:`${date}T09:45:00`,arrivalTime:`${date}T15:20:00`,departureHour:9,durationMinutes:335,stops:1,stopCity:"Frankfurt",pricePerAdult:178,pricePerChild:124,totalPrice:604,baggageIncluded:true,baggageDetails:"1 carry-on + 1 checked bag 23kg. Kids meal included",seatsTogether:true,isSelfTransfer:false,seatsAvailable:3},
    {airline:"British Airways",flightNumber:"BA163",origin,destination,departureTime:`${date}T13:15:00`,arrivalTime:`${date}T17:05:00`,departureHour:13,durationMinutes:290,stops:1,stopCity:"London",pricePerAdult:195,pricePerChild:137,totalPrice:664,baggageIncluded:true,baggageDetails:"1 carry-on + 1 checked bag 23kg. Priority family boarding",seatsTogether:true,isSelfTransfer:false,seatsAvailable:5},
    {airline:"Vueling",flightNumber:"VY6145",origin,destination,departureTime:`${date}T14:00:00`,arrivalTime:`${date}T17:25:00`,departureHour:14,durationMinutes:265,stops:0,pricePerAdult:112,pricePerChild:112,totalPrice:448,baggageIncluded:true,baggageDetails:"1 carry-on + 1 checked bag 20kg",seatsTogether:false,isSelfTransfer:false,seatsAvailable:6},
    {airline:"EasyJet",flightNumber:"EZY8831",origin,destination,departureTime:`${date}T16:30:00`,arrivalTime:`${date}T19:55:00`,departureHour:16,durationMinutes:265,stops:0,pricePerAdult:95,pricePerChild:95,totalPrice:380,baggageIncluded:false,baggageDetails:"Carry-on only. Checked bag 28 GBP/person. Seat selection 6 GBP/person",seatsTogether:false,isSelfTransfer:false,seatsAvailable:2},
    {airline:"Ryanair",flightNumber:"FR4420",origin,destination,departureTime:`${date}T06:15:00`,arrivalTime:`${date}T09:45:00`,departureHour:6,durationMinutes:270,stops:0,pricePerAdult:54,pricePerChild:54,totalPrice:216,baggageIncluded:false,baggageDetails:"Carry-on only. Checked bag 30 EUR/person. Seat selection 8 EUR/person",seatsTogether:false,isSelfTransfer:false,seatsAvailable:9},
    {airline:"Wizz Air",flightNumber:"W64421",origin,destination,departureTime:`${date}T22:00:00`,arrivalTime:`${date}T01:30:00`,departureHour:22,durationMinutes:270,stops:0,pricePerAdult:61,pricePerChild:61,totalPrice:244,baggageIncluded:false,baggageDetails:"Carry-on only. Checked bag 25 EUR/person. Seat selection 6 EUR/person",seatsTogether:false,isSelfTransfer:false,seatsAvailable:11},
    {airline:"EasyJet",flightNumber:"EZY1234",origin,destination,departureTime:`${date}T08:00:00`,arrivalTime:`${date}T13:30:00`,departureHour:8,durationMinutes:330,stops:1,stopCity:"Gatwick",pricePerAdult:72,pricePerChild:72,totalPrice:288,baggageIncluded:false,baggageDetails:"Carry-on only. SELF-TRANSFER at Gatwick - luggage not through-checked",seatsTogether:false,isSelfTransfer:true,seatsAvailable:6},
  ];
}
module.exports={getMockFlights};
